[package]
name = "digital-cash"
version = "0.0.0"
authors = ["Dharitri"]
edition = "2021"
publish = false

[lib]
path = "src/digital_cash.rs"

[dependencies.dharitri-sc]
version = "0.12.8"

[dev-dependencies.dharitri-sc-scenario]
version = "0.12.8"
